test

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -23,8 +23,18 @@ jobs:
       - name: Lint
         run: yarn nx format:check --all
         continue-on-error: true  # Continue even if the check fails
+      - name: Check Lint Results
+        id: lint_result_check
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Linting failed, setting output..."
+            echo "::set-output name=lint_failed::true"
+          else
+            echo "::set-output name=lint_failed::false"
+          fi
+
       - name: Auto-format and commit changes if needed
-        if: ${{ steps.lint_check.conclusion == 'failure' }}
+        if: ${{ steps.lint_result_check.outputs.lint_failed == 'true' }}
         run: |
           yarn nx format:write --all
           git config --global user.name "GitHub Actions"
