ci: add status check to linter as test

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -25,3 +25,18 @@ jobs:
         run: yarn install
       - name: Lint
         run: yarn nx format:check --all
+  check_status:
+    needs:
+      [
+        linter,
+      ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check status
+        working-directory: ${{ github.workspace }}
+        run: |
+          if [ ${{ needs.linter.result }} != 'success' ]; then
+              echo "Linting failed"
+              exit 1
+          fi
+          echo "All tests passed"
